### ISSUE TITLE
Femur head partially segmented as hips?

### ISSUE THREAD

**Issue by marcus-wirtz-snkeos** [wasserth/TotalSegmentator#103]
Is there a particular reason that the Femur head is not entirely contained in the Femur? A part of the femur head is always segmented as `hip_left` / `hip_right`. I checked this on 10 samples from https://zenodo.org/record/6802614 - the following screenshot is taken from patient with ID `S0091`:

![image](https://user-images.githubusercontent.com/24655255/232808799-24d43f30-30ae-49e8-b040-a653f99cb402.png)

**Comment by wasserth** [comment]
Automatically generated reponse by ChatGPT:

It's difficult to say without looking at the specific code and dataset, but it's possible that it's a result of the training data and/or the segmentation algorithm used. It's also possible that it's intentional, if the developers have determined that it produces better results overall. If it's a major issue for your specific use case, you could try contacting the developers and asking for more information or potentially modifying the code to address the issue.

The developers will manually answer your question if they think this answer is not sufficient.

**Comment by wasserth** [comment]
There is no specific reason for this missclassification. In the next version this will be improved.
