### ISSUE TITLE
Patient and scanning metadata availability

### ISSUE THREAD

**Issue by deepakri201** [wasserth/TotalSegmentator#12]
Hi, 

I was curious if it would be possible to have access to the patient and scanning metadata associated with each provided CT Nifti file. These would be attributes such as the ones in Figure 2 of your paper (distributions of age, gender, and scanning site). 

Thank you! 

Deepa

**Comment by wasserth** [comment]
This data is available in the `meta.csv` file in the dataset.

**Comment by tmathai** [comment]
Hello, thank you for making this dataset publicly available and I think your work is going to be pretty useful for a lot of applications. I looked at the `meta.csv` file in the dataset, and it contains information on the age, gender, institute, study type, and data_split. However, it doesn't contain information regarding the scanner, contrast phase used etc. Can we anticipate the release of this information? Please let me know! 

Thanks,
Tejas

**Comment by krekiehn** [comment]
Hi! 

I am also very interested in the contrast phase of the scans. Is there any information on this?

**Comment by tmathai** [comment]
@krekiehn I don’t think they released the info. Jakob just closed the comment thread without answering my earlier question. Your best bet is to use their phase prediction code “pi_time” to obtain the phase on the TS dataset. However, that will also not be useful because the CT volumes in the dataset are downsampled (lower resolution) from the original CT. The contrast agent may not be as clearly visible, which makes it harder to manually verify the phase as well. You are better off collecting your own dataset. Hope this helps.

**Comment by wasserth** [comment]
The contrast phase information is not available for the TotalSegmentator dataset. To train our phase prediction model we only partly used this dataset, since we did not have groundtruth for the entire dataset. Predicting the phase using our phase prediction model should work fairly well on the Totalsegmentator dataset even though it is downsampled to 1.5mm. This lower resolution should not have big impact on the result.
