### ISSUE TITLE
Label Overlap

### ISSUE THREAD

**Issue by zhi-xuan-chen** [wasserth/TotalSegmentator#121]
Is there any overlap of labels for different categories in the TotalSegmentator dataset? I noticed that some pixels seem to belong to multiple categories.

**Comment by wasserth** [comment]
Since totalsegmentator is using 5 models, some of the segmentations can overlap (but this should only be very little). If you use the --fast option, then totalsegmentator only uses 1 model and then there is not overlap.
The classes in the 5 different models can be seens here: Between models they can overlap. https://github.com/wasserth/TotalSegmentator/blob/master/totalsegmentator/map_to_binary.py#L396
