### ISSUE TITLE
Request for Clarity on User Data Logging

### ISSUE THREAD

**Issue by kbressem** [wasserth/TotalSegmentator#169]
Firstly, thank you for your dedication to this fantastic open-source tool. 

I recently noticed that there's been a new data logging behavior in v1.5.4. Although this change is documented in the README, it's subtle and easy to miss, especially if you do not check the README with every upgrade. 
At the moment, logging is on an 'opt-out' basis, where it's active by default and users must specifically deactivate it. This might not align with many users' privacy expectations.

Therefore, I'd like to ask for two changes:

- Switch the data logging to an 'opt-in' approach, ensuring it's off by default and users can enable it at their discretion.
- In addition to the README, introduce a clear notification within the tool itself, ideally during startup.

**Comment by fedorov** [comment]
FWIW, I took a quick look, and I do not see anything that would constitute user identifying information in the statistics collected: https://github.com/wasserth/TotalSegmentator/blob/master/totalsegmentator/config.py#L79-L95

The `send_usage_statistics` function is used here: https://github.com/wasserth/TotalSegmentator/blob/master/totalsegmentator/python_api.py#L217-L219, and `statistics` and `radiomics` parameters seem to be just the bool flags.

Given the nature of data being collected, I am not sure if "opt in" is mandated vs "opt out" (since if it is turned off by default, and most users don't care/won't notice, you will not get any stats by default). But I do agree that clear notification about the information being collected is very appropriate, most importantly to make sure this does not come across as if this usage collection is hidden intentionally.

Related discussion on the topic of usage data collection in 3D Slicer: https://discourse.slicer.org/t/should-we-start-collecting-software-usage-data/30873.

**Comment by wasserth** [comment]
Sorry for the late response. I was on vacation for the last two weeks.
These are valid considerations which I also spent some time thinking about.
In general it is extremely helpful to have some overal statistics: How many people are using the software, which platforms are used, which python versions are used, which features are used. This helps a lot to improve and further develop TotalSegmentator which in return benefits all of the users. Being able to show the number of users also helps to apply for further funding. This helps to keep on maintaining it.
If I change it to opt in probably 99% of the users will not activate it because of laziness which makes the entire statistics meaningless. Therefore, it has to stay opt out. And as @fedorov mentioned all the information which is collected is anonymous and can not be used to identify the user. It also does not contain any information about the data which is being processed.

I agree that it should be very clear to the user that this minimal information is being logged. I do not want to hide it from any user. At the same time I try to make the useability and documentation as easy as possible. So if I put the information about the statistics logging at the beginning of the Readme it will bloat the text somebody has to read before he can run the first example.  This is bad UX. Therefore, I put it at the end of the Readme because it is irrelevant for most people. 

I guess I will also add the following: The first time TotalSegmentator is run it will also show a message that statistics are collected per default. But this message will disappear when you run TotalSegmentator more often to not annoy the user.

**Comment by kbressem** [comment]
I think an initial message is a great idea! Given the type of data is completely anonymous most users will agree with it, I believe.
