### ISSUE TITLE
Inquiry regarding error while performing TotalSegmentator via Python API

### ISSUE THREAD

**Issue by Yeonjin-Jang** [wasserth/TotalSegmentator#170]
My name is Yeonjin Jang from Yonsei University in Korea.

I’m studying auto-segmentation using TotalSegmentator.
When attempting to execute the program via Python API, I faced an error as follows. Could you suggest a solution for this?

>>> from totalsegmentator.python_api import totalsegmentator
>>> totalsegmentator(r"C:\Users\user_name\Desktop\AutoSeg\CT_autoseg", r"C:\Users\user_name\Desktop\AutoSeg\Test")

If you use this tool please cite: https://pubs.rsna.org/doi/10.1148/ryai.230024

No GPU detected. Running on CPU. This can be very slow. The '--fast' option can help to some extend.
Converting dicom to nifti...
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    totalsegmentator(r"C:\Users\user_name\Desktop\AutoSeg\CT_autoseg", r"C:\Users\user_name\Desktop\AutoSeg\Test")
  File "C:\Python\lib\site-packages\totalsegmentator\python_api.py", line 212, in totalsegmentator
    quiet=quiet, verbose=verbose, test=test, skip_saving=skip_saving)
  File "C:\Python\lib\site-packages\totalsegmentator\nnunet.py", line 171, in nnUNet_predict_image
    dcm_to_nifti(file_in, tmp_dir / "dcm" / "converted_dcm.nii.gz", verbose=verbose)
  File "C:\Python\lib\site-packages\totalsegmentator\dicom_io.py", line 100, in dcm_to_nifti
    os.remove(str(output_path)[:-7] + ".json")
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다: 'C:\\Users\\user_name\\AppData\\Local\\Temp\\nnunet_tmp_b9axbvmp\\dcm\\converted_dcm.json'

I tried to resolve the error using the solutions posted on GitHub, but I am still encountering same issue.
Could this error be occurring because of running the program on Windows?
I would appreciate it if you could let me know the answer to my question.

Sincerely,
Yeonjin Jang.

**Comment by wasserth** [comment]
At the moment there is no easy solution unfortunately. 
You could clone the code locally, remove this line, and then install your local copy. Then it could work.
Or you use a different platform instead of windows (e.g. linux or mac). This is a Windows issue.

**Comment by suhrudp** [comment]
I am facing the same issue. How did you work around that?

**Comment by wasserth** [comment]
The easiest is to use nifti images as input instead of dicom images. You can use https://github.com/rordenlab/dcm2niix to convert your dicom images to nifti. This issue does not occur with nifti images.

**Comment by suhrudp** [comment]
**Thank you for the prompt response!**

ef dicom_to_nifti(input_path, output_path):
    dicom_files = [os.path.join(input_path, f) for f in os.listdir(input_path) if f.endswith('.dcm')]

    pixel_data = [pydicom.dcmread(f).pixel_array for f in dicom_files]

    pixel_data_3d = np.stack(pixel_data)

    nifti_img = nib.Nifti1Image(pixel_data_3d, np.eye(4))

    nib.save(nifti_img, output_path)

def main():
    base_input_path = "/content/drive/MyDrive/train_images/"
    base_output_path = "/content/drive/MyDrive/segmentations/"

    patient_folders = [os.path.join(base_input_path, f) for f in os.listdir(base_input_path) if os.path.isdir(os.path.join(base_input_path, f))]

    for patient_folder in patient_folders:
        patient_number = os.path.basename(patient_folder)

        series_folders = [os.path.join(patient_folder, f) for f in os.listdir(patient_folder) if os.path.isdir(os.path.join(patient_folder, f))]

        for series_folder in series_folders:
            series_name = os.path.basename(series_folder)

            output_path = os.path.join(base_output_path, patient_number, series_name)
            os.makedirs(output_path, exist_ok=True)

            nifti_file_path = os.path.join(output_path, f"{series_name}.nii")
            dicom_to_nifti(series_folder, nifti_file_path)

            totalsegmentator(nifti_file_path, output_path, ml=True)

if __name__ == "__main__":
    main()
    
**this is the code I used to do so.
however, the issue** 

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-3-8906d9c8510d>](https://localhost:8080/#) in <cell line: 48>()
     47 
     48 if __name__ == "__main__":
---> 49     main()

3 frames
[<ipython-input-3-8906d9c8510d>](https://localhost:8080/#) in main()
     41             
     42             nifti_file_path = os.path.join(output_path, f"{series_name}.nii")
---> 43             dicom_to_nifti(series_folder, nifti_file_path)
     44 
     45             

[<ipython-input-3-8906d9c8510d>](https://localhost:8080/#) in dicom_to_nifti(input_path, output_path)
      7 
      8     
----> 9     pixel_data_3d = np.stack(pixel_data)
     10 


/usr/local/lib/python3.10/dist-packages/numpy/core/overrides.py in stack(*args, **kwargs)

[/usr/local/lib/python3.10/dist-packages/numpy/core/shape_base.py](https://localhost:8080/#) in stack(arrays, axis, out)
    420     arrays = [asanyarray(arr) for arr in arrays]
    421     if not arrays:
--> 422         raise ValueError('need at least one array to stack')
    423 
    424     shapes = {arr.shape for arr in arrays}

ValueError: need at least one array to stack

**It worked fine for 3 files, and then gave such an error.
The dicom directories are fine and working in 3D slicer where I ran TotalSegmentator which works like a charm. However, to automate the process, I would need to use python to loop.

Could you please provide any other suggestions?
Thank you again!**

**Comment by Brian-Taylor8** [comment]
Hey, I'm not the author of this repo, but I'd recommend using a dicom to nifti package to convert it. It feels like your script has an issue with how you sliced it, but it may also have an issue with the affine. The affine function that you fed to your nifti image upon it's creation is the identity and won't be accurate(the affine you gave is np.eye(4) in the line: nifti_img = nib.Nifti1Image(pixel_data_3d, **np.eye(4)**). May also be due to how you combined your slices, but that'd also be fixed by using a package.
The affine is apparently fairly important to `TotalSegmentator` cuz it translates from voxel space to real world space(I believe this must give the model some idea of scale and orientation?). Anyway, one such way to convert is with [dicom2nifti](https://github.com/icometrix/dicom2nifti):
```python
import dicom2nifti
dicom2nifti.convert_directory(path_to_dicom_series, path_to_save_nifti_file)
```
Personally I've encountered wacky affines causing all sorts of errors. It's possible that the identity matrix isn't causing your error specifically, but you will definitely want to use a package to convert(another one, used by this repo for ex, is dcm2niix), because your results won't be as accurate without a proper affine, even if you fix that specific error and get the algo to run successfully.


On another note, the python api seems to also be broken on windows for me, and I'm feeding it straight NIFTI files that work fine through the regular `TotalSegmentator` script. Like, `TotalSegmentator -i inputNIfTI -o outputNIfTI` is working swimmingly, but `totalsegmentator(inputNIfTI, outputNIfTI)` seems to result in what looks like a threading error? The readout is something along the lines of:
```
...\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Exception ignored in: <totalsegmentator.libs.DummyFile object at 0x00000212DEA35F70>
AttributeError: 'DummyFile' object has no attribute 'flush'
...
```
And it also reruns lines from earlier in my program and seems to loop forever.  @suhrudp, did you say you got a couple NIFTIs to run successfully through the python API? Have you come across any errors like this by any chance?

**Comment by wasserth** [comment]
In TotalSegmentator v2 I use a different package to convert dicom to nifti internally. So now it should also properly work on windows. You can try again directly giving a dicom folder as input to TotalSegmentator.
