### ISSUE TITLE
V1 branch with appropriate pip install

### ISSUE THREAD

**Issue by ibro45** [wasserth/TotalSegmentator#179]
It would be useful to have a branch to the TotalSegmentator v1 along with `pip install` set to the appropriate TotalSegmentator version, similarly to what nnUNet did when they introduced their v2.

**Comment by wasserth** [comment]
I think a separate branch + separate pip package is not needed for that. Having two pip packages will rather confuse people: Imagine having a package numpyv1 and numpyv2. 
Pip allows to install specific versions of a package, so this is the best solution in my opinion. If you want to run totalsegmentator v1 just install the latest v1 package: `pip install totalsegmentator==1.5.6`

**Comment by ibro45** [comment]
Indeed, that's what I meant for pip. However, one would still want to check the docs of v1, hence the branch. Particularly useful if someone is comparing what is described in your Radiology AI paper with the code, as suddenly it will be different, and not easy to find/use the model described in the paper.

**Comment by wasserth** [comment]
This is a tradeoff: Spend time building new features and adding new classes or spend time to maintain v1 to make everything as reproducible as possible. I think the benefit for the community is larger if I use my time to built new features / add more classes.
Therefore, I am mainly focused on v2. If there should occur a major bug which makes v1.5.6 stop working, then I will fix it. I hope that 1.5.6 will keep on working for a few more years without requiring major changes. So if people rely on it, they do not have to upgrade to v2 in the near future.

The changes of v2 are described in more detail here: https://github.com/wasserth/TotalSegmentator/blob/master/resources/improvements_in_v2.md

I do not plan to write a paper about v2 because the methods are just identical to v1. We just added more data and classes. So basically the v1 paper also applies for v2. There are a few minor changes, but they are described in the readme I mentioned above. Writing another paper about these minor changes would cost me months of work for almost no benefit for the community (which is equal to almost no benefit for society, which is equal to wasting tax money because I am mainly funded by public research money ;) ).

**Comment by ibro45** [comment]
Indeed, I completely agree with you @wasserth, I was initially suggesting just to have a clearer distinction of v1 - a section in the current README with a link to v1.5.6 commit and `pip install TotalSegmentator=1.5.6` would suffice.

Thanks for all the work!

**Comment by denbonte** [comment]
> I was initially suggesting just to have a clearer distinction of v1 - a section in the current README with a link to v1.5.6 commit and pip install TotalSegmentator=1.5.6 would suffice.

Absolutely - I think nnU-Net has another branch with it 🙃 

> I do not plan to write a paper about v2 because the methods are just identical to v1. We just added more data and classes. So basically the v1 paper also applies for v2. There are a few minor changes, but they are described in the readme I mentioned above. Writing another paper about these minor changes would cost me months of work for almost no benefit for the community

@wasserth I see your point, and I think it's very valid! I did not see the last section of that README, my bad - thanks for adding the metadata for the training data, the evaluation code, etc. 😄

> This is a tradeoff: Spend time building new features and adding new classes or spend time to maintain v1 to make everything as reproducible as possible. I think the benefit for the community is larger if I use my time to built new features / add more classes.
Therefore, I am mainly focused on v2. If there should occur a major bug which makes v1.5.6 stop working, then I will fix it. I hope that 1.5.6 will keep on working for a few more years without requiring major changes. So if people rely on it, they do not have to upgrade to v2 in the near future.

It makes sense - and again, nnU-Net did something very similar, and I think it makes total sense. The reason I was asking is we just want to know how to best develop our pipeline around TotalSegmentator (which means understanding how fast we should switch to v2 from v1, and how to deal with the results and resources we developed around v1). I hope I did not come across the wrong way on this!

Thanks again!

**Comment by wasserth** [comment]
I added a section to the readme which shows how to install v1 and I also added a link to the documentation of v1. I think this is an important addon for the documentation. Thank you very much for pointing this out! Upgrading tools which are part of your pipeline is always a pain. I know this from my own experience. I want to reduce this pain as much as possible for people using TotalSegmentator.
