### ISSUE TITLE
Segment names not available in Slicer after command line segmentation

### ISSUE THREAD

**Issue by lennart81** [wasserth/TotalSegmentator#294]
Hi there,

I'm not sure if this is the best forum to add this but I would like to run segmentation on a linux server and review the files in slicer on a windows machine. Is it possible to have the organ names imported as well to 3D Slicer? 

Thanks!

**Comment by francescopisu** [comment]
What do you mean by "organ names imported as well to 3D Slicer" ? Would you like to have the organ names instead of "Segment_1", "Segment_2" etc ?

<img width="1144" alt="Screenshot 2024-04-21 alle 16 58 38" src="https://github.com/wasserth/TotalSegmentator/assets/14362976/93d24c36-2878-4acf-8407-f6cf06899950">

**Comment by lennart81** [comment]
yes exactly! I solved it by using a custom color table.

Is there a listing of all models and subsets?
