### ISSUE TITLE
Question regarding the --roi_subset accuracy.

### ISSUE THREAD

**Issue by maksymfritsak** [wasserth/TotalSegmentator#367]
In your README, it is specified that --roi_subset might be less accurate, especially for small classes (e.g., prostate).

Is the accuracy lower because the model makes predictions on other derived structures, and when predicting only the prostate, the model does not have other structures to use as "support" for the segmentation?

**Comment by wasserth** [comment]
It can be lower, because first a lower resolution model searches the organ and then the image is cropped to the organs and then the highres model is run on this smaller crop. The highres model has the same accuracy. But it can happen that the lower resolution model does not find the organ properly and then the crop is wrong.
