### ISSUE TITLE
Web version questions

### ISSUE THREAD

**Issue by terrielsimmons** [wasserth/TotalSegmentator#42]
I have already used the Total Segmentator module in 3D Slicer on smaller CTs, but I am trying out the web version on a full body CT. I opened the NRRD volume with 3D Slicer and saved it as nii.gz to upload. It's been sitting all day (see image). How long should I expect to wait and does this mean there's an issue with my nii.gz? I opened it in 3D Slicer and it looks fine.
![2022-12-23_15-12-45](https://user-images.githubusercontent.com/46006221/209401961-e9da7240-5ef2-402f-bf22-cd4f4fa60fea.png)

**Comment by joshy** [comment]
That should not happen and looks like it is stuck at the upload. Can you try with another data set? I am not at work but will look into it after the christmas holidays.Best regards,Joshy--Sent from phoneOn 23 Dec 2022, at 21:16, Terrie Simmons-Ehrhardt ***@***.***> wrote:﻿
I have already used the Total Segmentator module in 3D Slicer on smaller CTs, but I am trying out the web version on a full body CT. I opened the NRRD volume with 3D Slicer and saved it as nii.gz to upload. It's been sitting all day (see image). How long should I expect to wait and does this mean there's an issue with my nii.gz? I opened it in 3D Slicer and it looks fine.

**Comment by terrielsimmons** [comment]
Thank you for responding! I'll try other datasets.

**Comment by joshy** [comment]
Hi, the website is running for other datasets. Have you tried with another dataset? If it is possible for you to share the problematic dataset I can investigate what the problem is.

**Comment by terrielsimmons** [comment]
Yes smaller datasets have worked. This one was a full body CT. I ended up trying it in 3D Slicer and it worked--there were extra/duplicate parts but I was able to delete them. The nrrd I downloaded was from Embodi3D: https://www.embodi3d.com/files/file/29386-skull-5th-attempt/.
<img width="407" alt="2022-12-27_7-18-17" src="https://user-images.githubusercontent.com/46006221/209709893-868b9462-9bcd-4334-9d90-c8f5531ff247.png">

**Comment by wasserth** [comment]
For very big full body images the website is not working.
For your image there are several segmentations in the background because your images contains a lot more background than the typical CT image. This problem can probably be solved by using the option `--body_seg`. This will first run a quick body segmentation and then only run the TotalSegmentator inside of this body segmentation. This should remove those other segmentation. This option is only available in the master branch so far. So you will have to install from this: https://github.com/wasserth/TotalSegmentator#install-latest-master-branch-contains-latest-bug-fixes

**Comment by terrielsimmons** [comment]
Thanks so much for taking a look at the CT! I'll try running with your suggestion.
