### ISSUE TITLE
run the totalsegmentor code programmatically

### ISSUE THREAD

**Issue by kmordhwaj** [wasserth/TotalSegmentator#47]
Hi @wasserth,
I am trying to write code and make a simple flask app and added a template app.html, and there picked a file from input file form and then running that on preview_image url of server.py file and putting that input file. But there in server.py codes subprocess.call(
        f"TotalSegmentator -i {input_file} -o {seg_dir} -f -p {stats} -ns 1", shell=True) is not working and giving error "TotalSegmentator is not an internal or external command"

Please help.

**Comment by wasserth** [comment]
You have to install TotalSegmentator first so it is available on the command line. 
Subprocess.call is just running this command on the command line.

**Comment by marvnmtz** [comment]
@kmordhwaj 
Since I struggled with the same issue, here is my solution so far:
I cloned the Github repo. Then in the bin-folder there is the file TotalSegmentator. I moved it to the totalsegmentator-folder and gave it the ending .py, so that it gets recognized when installing the TotalSegmentator in my conda environment. Then you can call TotalSegmentator.totalsegmentator.main() from within your python script. 

@wasserth: Since all the coding is actually written in Python, is there a more elegant way to use the TotalSegmentator as a python function or is that featured planned for the future?

**Comment by kmordhwaj** [comment]
Thanks @marvnmtz

**Comment by wasserth** [comment]
You could look into the python code and call the python methods yourself. But this is also not very elegant or easy. We can try to add a python API in the next version.
